// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/app-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var app_info_default = defineTool({
  name: "app_info",
  title: "App info",
  description: "Return a short description of the SODATRA Bank Sync Flow application, its purpose and available modules.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "SODATRA Bank Sync Flow \u2014 internal banking data centralization app.",
          "",
          "Purpose: import, control and exploit banking data from manual Excel/PDF uploads",
          "(collection reports, fund positions, client reconciliation, BDK/BIS/SGS/BICIS/ORA/ATB",
          "bank statements, unpaid items, drafts, cheques).",
          "",
          "Active modules:",
          "- /dashboard \u2014 main dashboard",
          "- /upload \u2014 file import pipeline",
          "- /document-understanding \u2014 BDK PDF analysis",
          "- /quality-control \u2014 data quality checks",
          "- /reconciliation \u2014 sync & collections reconciliation",
          "",
          "Access: invite-only, mono-tenant. No direct bank API connection."
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sodatra-bank-sync-flow-mcp",
  title: "SODATRA Bank Sync Flow MCP",
  version: "0.1.0",
  instructions: "MCP server for the SODATRA Bank Sync Flow app. Use `app_info` to get a description of the application, its purpose and available modules. No user data is exposed through this server.",
  tools: [app_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
